

---
- name: Create test files and set permissions
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: "0750"
  loop:
    - /tmp/testme-1.py
    - /tmp/testme-2.py


